name: CI/CD Pipeline

on:
  push:
    branches:
      - wisecow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CODE CHECKOUT
        uses: actions/checkout@v2

      - name: SET UP DOCKER BUILDx
        uses: docker/setup-buildx-action@v3

      - name: LOGIN DOCKER HUB
        run: |
          echo "Logging into Docker Hub.."
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "Logged in to Docker Hub."

      - name: BUILD AND PUSH DOCKER IMAGE
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rameshxt/wisecow:v1.0.${{ github.run_number }}
          context: .

      - name: UPDATE IMAGE TAG IN Deployment.yaml
        run: |
          IMAGE_TAG="rameshxt/wisecow:v1.0.${GITHUB_RUN_NUMBER}"
          echo "Updating image tag in deployment.yam with: $IMAGE_TAG"
          bash image-updater.sh "$IMAGE_TAG"
          echo "deployment.yaml updated successfully."

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Cleaning EC2 instance and preserving Minikube..."

            echo "Removing WISECOW-DEPLOYMENT directory..."
            sudo rm -rf /home/ec2-user/WISECOW-DEPLOYMENT

            echo "Stopping all containers except 'minikube'..."
            docker ps -a --format '{{.ID}} {{.Names}}' | grep -v minikube | awk '{print $1}' | xargs -r docker stop || true

            echo "Removing all containers except 'minikube'..."
            docker ps -a --format '{{.ID}} {{.Names}}' | grep -v minikube | awk '{print $1}' | xargs -r docker rm || true

            echo "Removing all images except 'gcr.io/k8s-minikube/kicbase:v0.0.46'..."
            docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep -v 'gcr.io/k8s-minikube/kicbase:v0.0.46' | awk '{print $2}' | xargs -r docker rmi -f || true

            echo "Clone the repository..."
            git clone https://github.com/RameshXT/WISECOW-DEPLOYMENT.git

            echo "UPDATE IMAGE TAG IN Deployment.yaml"
            cd /home/ec2-user/WISECOW-DEPLOYMENT
            bash image-updater.sh "$IMAGE_TAG"

            echo "Deploying the application on Kubernetes..."
            kubectl apply -f /home/ec2-user/WISECOW-DEPLOYMENT/k8s/deployment.yaml
            kubectl apply -f /home/ec2-user/WISECOW-DEPLOYMENT/k8s/service.yaml

            echo "Deployment completed successfully."
            # echo "Waiting for the service to be available..."
            # while ! kubectl get service wisecow-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'; do
            #   echo "Waiting for the service to be available..."
            #   sleep 10
            # done
            # echo "Service is available."
